### ISSUE TITLE
Wrong python lower bound

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pyqtgraph-feedstock#30]
Upstream dropped python 3.8 as of https://github.com/pyqtgraph/pyqtgraph/commit/785e6413b51dbf2ba4b3050aaf11873fd90280e2, but the metadata in `meta.yaml` still claims it's compatible. This leads to failures such as:
```
    import pyqtgraph as pg
  File "$SP_DIR/pyqtgraph/__init__.py", line 205, in <module>
    from .graphicsItems.AxisItem import *
  File "$SP_DIR/pyqtgraph/graphicsItems/AxisItem.py", line 11, in <module>
    from .GraphicsWidget import GraphicsWidget
  File "$SP_DIR/pyqtgraph/graphicsItems/GraphicsWidget.py", line 2, in <module>
    from .GraphicsItem import GraphicsItem
  File "$SP_DIR/pyqtgraph/graphicsItems/GraphicsItem.py", line 40, in <module>
    class GraphicsItem(object):
  File "$SP_DIR/pyqtgraph/graphicsItems/GraphicsItem.py", line 612, in GraphicsItem
    nodes: dict[str, Element]
TypeError: 'type' object is not subscriptable
```

**Comment by j9ac9k** [comment]
Oh right, should update that.

**Comment by h-vetinari** [comment]
This also needs a repodata patch, because the currently published build would still be pulled in for 3.8 even if you now publish a new one with a >=3.9 constraing. Here's an [example](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/697) of how to do this - please create such a PR as well (you can ping me there if you need help).

**Comment by h-vetinari** [comment]
Thanks for #31!

We still need an equivalent of the following though:

> This also needs a repodata patch, because the currently published build would still be pulled in for 3.8 even if you now publish a new one with a >=3.9 constraing. Here's an [example](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/697) of how to do this - please create such a PR as well (you can ping me there if you need help).

**Comment by j9ac9k** [comment]
I added 

> Thanks for #31!
> 
> We still need an equivalent of the following though:
> 
> > This also needs a repodata patch, because the currently published build would still be pulled in for 3.8 even if you now publish a new one with a >=3.9 constraing. Here's an [example](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/697) of how to do this - please create such a PR as well (you can ping me there if you need help).

is that not what this file does? https://github.com/conda-forge/pyqtgraph-feedstock/pull/31/files#diff-0491d1db1d688b45e9a85e2726f32341199626bb1fff4905a81a34296df6085e

**Comment by ryanvolz** [comment]
Sorry to say I'm still seeing this over at https://github.com/conda-forge/gnuradio-feedstock/pull/262, probably because the run dep is still `python >=3.8` even after #31! Another updated build is needed with that change, and then I think another repodata patch for build number 1 now as well.

**Comment by j9ac9k** [comment]
> Sorry to say I'm still seeing this over at [conda-forge/gnuradio-feedstock#262](https://github.com/conda-forge/gnuradio-feedstock/pull/262), probably because the run dep is still `python >=3.8` even after #31! Another updated build is needed with that change, and then I think another repodata patch for build number 1 now as well.

Huh, I bumped the build version, re-rendered with the new python 3.9 dependency.

FWIW I'm about to roll a new version of pyqtgraph (like today or tomorrow if all goes well), that will have a build version of 0, and have a python requirement of 3.9+.

**Comment by j9ac9k** [comment]
> This is the part that needs to read 3.9 instead of 3.8: https://github.com/conda-forge/pyqtgraph-feedstock/blob/c5c52425681881684014e8599f82f07a573e59fc/recipe/meta.yaml#L24.
> 
> 
> 
> A new release will definitely solve the problem, provided that the above line is also updated!

Wow, how did I miss that... that's what I get for working on these things late at night.

Thanks for pointing out the issue!

**Comment by h-vetinari** [comment]
> Wow, how did I miss that... that's what I get for working on these things late at night.

We need another repodata patch for build `_1` now...

**Comment by h-vetinari** [comment]
Ah, just saw https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/713, thanks!
