### ISSUE TITLE
Depend on Qt6?

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/pyqtgraph-feedstock#36]
Hello, the upstream package is now supporting Qt6 with PySide6 bindings. Would it be possible to adjust the dependencies here accordingly, given that PySide6 and Qt6 have been out for a long time and are meanwhile available from conda-forge?

An alternative could be to produce two build outputs: One depending on PySide2, the other on PySide6. WDYT?

**Comment by j9ac9k** [comment]
I forgot that there is a pyside6 conda package, feel free to submit a PR updating the required dependencies, it may be a few days before I get to it.

**Comment by hoechenberger** [comment]
Actually, I just realized you don't have a "hard" dependency on PySide2 / PyQt currently anyway

So there's no need to add PySide6 anywhere – if the user opts to install it, pyqtgraph should pick it up automatically.

I think this issue can therefore be closed
